"use client";

import React from "react";
import { VylosLogo } from "../ui/VylosLogo";

export function TermsAndConditions() {
  return (
    <div className="space-y-8 text-text-main leading-relaxed">
      <div className="flex flex-col items-center text-center gap-4 mb-12">
        <div className="mb-2">
          <VylosLogo iconOnly size="large" />
        </div>
        <h1 className="text-4xl font-black tracking-tighter">Vylos</h1>
        <p className="text-sm font-bold text-primary uppercase tracking-widest">Track. Understand. Improve. Grow.</p>
      </div>

      <section className="space-y-4">
        <h2 className="text-2xl font-black tracking-tight text-text-main border-l-4 border-primary pl-4">VYLOS TERMS AND CONDITIONS</h2>
        <div className="grid grid-cols-2 gap-4 text-xs font-bold text-text-muted uppercase tracking-wider bg-card p-4 rounded-2xl border border-border-main">
          <div>Effective Date: May 26, 2026</div>
          <div>Last Updated: May 26, 2026</div>
        </div>
      </section>

      <section className="space-y-4">
        <h3 className="text-xl font-black text-text-main">1. Introduction</h3>
        <p>Welcome to Vylos.</p>
        <p>These Terms and Conditions govern your access to and use of the Vylos website, platform, dashboard, mobile application, web application, software, tools, features, reports, content, and related services.</p>
        <p>By accessing or using Vylos, you agree to be bound by these Terms. If you do not agree with these Terms, you must not use the platform.</p>
        <p>Vylos is designed to help users track, organise, understand, and manage financial information through dashboards, reports, transaction tracking, budgeting tools, goal tracking, reminders, and financial visibility features.</p>
        <div className="p-4 bg-amber-500/10 border border-amber-500/20 rounded-2xl">
          <p className="text-sm font-bold text-amber-500 italic">Vylos is not a bank, credit provider, insurer, investment provider, tax advisor, accountant, or licensed financial adviser unless expressly stated in writing.</p>
        </div>
      </section>

      <section className="space-y-4">
        <h3 className="text-xl font-black text-text-main">2. Definitions</h3>
        <ul className="space-y-3 list-decimal pl-5 marker:font-black">
          <li><span className="font-bold">"Vylos", "we", "us", or "our"</span> means Vylos.</li>
          <li><span className="font-bold">"User", "you", or "your"</span> means any person, business, organisation, or authorised representative who accesses or uses Vylos.</li>
          <li><span className="font-bold">"Platform"</span> means the Vylos website, web application, mobile application, dashboard, software, tools, features, and related services.</li>
          <li><span className="font-bold">"Account"</span> means a registered user profile created to access Vylos.</li>
          <li><span className="font-bold">"Financial Data"</span> means information entered, uploaded, imported, connected, or generated through Vylos.</li>
          <li><span className="font-bold">"Content"</span> means text, graphics, dashboards, reports, templates, insights, designs, software, logos, documents, and other material.</li>
          <li><span className="font-bold">"Subscription"</span> means any paid plan or recurring service offered by Vylos.</li>
        </ul>
      </section>

      <section className="space-y-4">
        <h3 className="text-xl font-black text-text-main">3. About Vylos</h3>
        <p>Vylos is a financial visibility and tracking platform. The platform may allow users to track transactions, categorise income and expenses, create budgets, set goals, view spending patterns, generate reports, and more.</p>
        <p>Vylos helps users understand their financial behaviour, but the user remains responsible for all financial decisions made outside or inside the platform.</p>
      </section>

      <section className="space-y-4">
        <h3 className="text-xl font-black text-text-main">4. No Financial Advice</h3>
        <p>Vylos does not provide personalised financial advice, investment advice, tax advice, legal advice, accounting advice, insurance advice, credit advice, or debt counselling.</p>
        <p>Any insights, summaries, reports, reminders, or suggestions generated by Vylos are provided for <span className="font-bold underline decoration-primary/30">general informational and educational purposes only</span>.</p>
        <p>You remain fully responsible for your financial decisions, spending, savings, investments, tax submissions, and business decisions.</p>
      </section>

      <section className="space-y-4">
        <h3 className="text-xl font-black text-text-main">5. No Banking, Credit, Insurance, or Investment Service</h3>
        <p>Unless clearly stated in writing and supported by the required authorisations, Vylos does not hold customer deposits, operate as a bank, issue loans, provide insurance, or sell investment products.</p>
        <p>Vylos is not a registered financial services provider under the Financial Sector Conduct Authority unless otherwise stated.</p>
      </section>

      <section className="space-y-4">
        <h3 className="text-xl font-black text-text-main">6. Eligibility</h3>
        <p>To use Vylos, you must be at least 18 years old (or have guardian permission), have legal capacity, provide accurate information, and use the platform lawfully.</p>
      </section>

      <section className="space-y-4">
        <h3 className="text-xl font-black text-text-main">7. Account Registration</h3>
        <p>You agree to provide accurate information, keep login details confidential, and notify us of any unauthorised access. You are responsible for all activity under your account.</p>
      </section>

      <section className="space-y-4">
        <h3 className="text-xl font-black text-text-main">8. User Responsibilities</h3>
        <p>You agree not to use Vylos for unlawful, fraudulent, or harmful purposes. You must not interfere with security, reverse engineer the platform, or upload malicious code.</p>
      </section>

      <section className="space-y-4">
        <h3 className="text-xl font-black text-text-main">9. User Data and Financial Information</h3>
        <p>You are responsible for the accuracy and legality of the data you provide. Vylos is not responsible for inaccurate results caused by incorrect user data.</p>
      </section>

      <section className="space-y-4">
        <h3 className="text-xl font-black text-text-main">10. Privacy and POPIA Compliance</h3>
        <p>Vylos respects user privacy and aims to process personal information in line with the Protection of Personal Information Act, 2013 (POPIA).</p>
        <p>Personal information processed may include name, email, phone, financial information, and usage data as detailed in our Privacy Policy.</p>
      </section>

      <section className="space-y-4">
        <h3 className="text-xl font-black text-text-main">11. Security</h3>
        <p>Vylos takes reasonable technical and organisational measures to protect user data, including encryption and access controls. However, no digital system is completely secure.</p>
      </section>

      <section className="space-y-4">
        <h3 className="text-xl font-black text-text-main">12. Third-Party Services</h3>
        <p>Vylos may connect to third-party services (hosting, auth, payments). Vylos is not responsible for the conduct or downtime of these third-party providers.</p>
      </section>

      <section className="space-y-4">
        <h3 className="text-xl font-black text-text-main">13. Uploads, Imports, and Integrations</h3>
        <p>You confirm you have the right to upload any data (CSV, bank statements) and that it is accurate and not fraudulent.</p>
      </section>

      <section className="space-y-4 border-t border-border-main pt-8">
        <h3 className="text-xl font-black text-text-main">14. Limitation of Liability</h3>
        <p className="font-bold text-sm">To the maximum extent permitted by law, Vylos is not liable for financial losses, business losses, loss of profits, or incorrect decisions made by users.</p>
        <p>Vylos' total liability is limited to the amount paid by the user in the previous three months.</p>
      </section>

      <section className="space-y-4">
        <h3 className="text-xl font-black text-text-main">15. Governing Law</h3>
        <p>These Terms are governed by the laws of the Republic of South Africa.</p>
      </section>

      <div className="p-8 bg-card border border-border-main rounded-[2.5rem] mt-12">
        <p className="text-xs font-medium text-text-muted text-center leading-relaxed">
          For any questions regarding these Terms, please contact support through the platform's help center.
        </p>
      </div>
    </div>
  );
}
